# Config.pri file version 2.0. Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR = $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        } else {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }

    }

    CONFIG(release, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

simulator {
    CONFIG(debug, debug|release) {
        !profile {
            CONFIG += \
                config_pri_assets \
                config_pri_source_group1
        }
    }
}

config_pri_assets {
    OTHER_FILES += \
        $$quote($$BASEDIR/assets/About.qml) \
        $$quote($$BASEDIR/assets/ChannelMemberList.qml) \
        $$quote($$BASEDIR/assets/ChatCard.qml) \
        $$quote($$BASEDIR/assets/DmList.qml) \
        $$quote($$BASEDIR/assets/LoginPage.qml) \
        $$quote($$BASEDIR/assets/MainPage.qml) \
        $$quote($$BASEDIR/assets/MessageBubble.qml) \
        $$quote($$BASEDIR/assets/ServerList.qml) \
        $$quote($$BASEDIR/assets/UserSheet.qml) \
        $$quote($$BASEDIR/assets/icon.png) \
        $$quote($$BASEDIR/assets/images/default-avt.png) \
        $$quote($$BASEDIR/assets/images/demo.png) \
        $$quote($$BASEDIR/assets/images/icons/accent/caret-left.png) \
        $$quote($$BASEDIR/assets/images/icons/accent/users.png) \
        $$quote($$BASEDIR/assets/images/icons/action_delete.png) \
        $$quote($$BASEDIR/assets/images/icons/caret-down.png) \
        $$quote($$BASEDIR/assets/images/icons/first.png) \
        $$quote($$BASEDIR/assets/images/icons/hash.png) \
        $$quote($$BASEDIR/assets/images/icons/house.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_edit.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_info.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_open.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_reply.png) \
        $$quote($$BASEDIR/assets/images/icons/ic_sign_out.png) \
        $$quote($$BASEDIR/assets/images/icons/paperclip-disabled.png) \
        $$quote($$BASEDIR/assets/images/icons/paperclip-hold.png) \
        $$quote($$BASEDIR/assets/images/icons/paperclip.png) \
        $$quote($$BASEDIR/assets/images/icons/send.png) \
        $$quote($$BASEDIR/assets/images/icons/speaker.png) \
        $$quote($$BASEDIR/assets/images/icons/x-disabled.png) \
        $$quote($$BASEDIR/assets/images/icons/x-hold.png) \
        $$quote($$BASEDIR/assets/images/icons/x.png) \
        $$quote($$BASEDIR/assets/main.qml)
}

config_pri_source_group1 {
    SOURCES += \
        $$quote($$BASEDIR/src/applicationui.cpp) \
        $$quote($$BASEDIR/src/core/AppStore.cpp) \
        $$quote($$BASEDIR/src/core/AttachmentImageCacheWorker.cpp) \
        $$quote($$BASEDIR/src/core/AvatarCacheWorker.cpp) \
        $$quote($$BASEDIR/src/core/Client.cpp) \
        $$quote($$BASEDIR/src/core/client/AvatarManager.cpp) \
        $$quote($$BASEDIR/src/core/client/AvatarState.cpp) \
        $$quote($$BASEDIR/src/core/client/CacheManager.cpp) \
        $$quote($$BASEDIR/src/core/client/ClientState.cpp) \
        $$quote($$BASEDIR/src/core/client/GatewayHandler.cpp) \
        $$quote($$BASEDIR/src/core/client/ItemMapper.cpp) \
        $$quote($$BASEDIR/src/core/client/MessageCache.cpp) \
        $$quote($$BASEDIR/src/core/client/SortUtils.cpp) \
        $$quote($$BASEDIR/src/core/discord/DiscordUtils.cpp) \
        $$quote($$BASEDIR/src/core/discord/Gateway.cpp) \
        $$quote($$BASEDIR/src/core/discord/GatewayEvents.cpp) \
        $$quote($$BASEDIR/src/core/discord/JsonParser.cpp) \
        $$quote($$BASEDIR/src/core/discord/NetworkWorker.cpp) \
        $$quote($$BASEDIR/src/core/discord/RestClient.cpp) \
        $$quote($$BASEDIR/src/core/discord/RestClientRequests.cpp) \
        $$quote($$BASEDIR/src/core/models/Models.cpp) \
        $$quote($$BASEDIR/src/main.cpp) \
        $$quote($$BASEDIR/src/ui/ChatController.cpp) \
        $$quote($$BASEDIR/src/ui/DmListController.cpp) \
        $$quote($$BASEDIR/src/ui/MainPageController.cpp) \
        $$quote($$BASEDIR/src/ui/ServerListController.cpp)

    HEADERS += \
        $$quote($$BASEDIR/src/applicationui.hpp) \
        $$quote($$BASEDIR/src/core/AppStore.hpp) \
        $$quote($$BASEDIR/src/core/AttachmentImageCacheWorker.hpp) \
        $$quote($$BASEDIR/src/core/AvatarCacheWorker.hpp) \
        $$quote($$BASEDIR/src/core/Client.hpp) \
        $$quote($$BASEDIR/src/core/client/AvatarManager.hpp) \
        $$quote($$BASEDIR/src/core/client/AvatarState.hpp) \
        $$quote($$BASEDIR/src/core/client/CacheManager.hpp) \
        $$quote($$BASEDIR/src/core/client/ClientState.hpp) \
        $$quote($$BASEDIR/src/core/client/GatewayHandler.hpp) \
        $$quote($$BASEDIR/src/core/client/ItemMapper.hpp) \
        $$quote($$BASEDIR/src/core/client/MessageCache.hpp) \
        $$quote($$BASEDIR/src/core/client/SortUtils.hpp) \
        $$quote($$BASEDIR/src/core/discord/DiscordUtils.hpp) \
        $$quote($$BASEDIR/src/core/discord/Gateway.hpp) \
        $$quote($$BASEDIR/src/core/discord/JsonParser.hpp) \
        $$quote($$BASEDIR/src/core/discord/NetworkWorker.hpp) \
        $$quote($$BASEDIR/src/core/discord/RestClient.hpp) \
        $$quote($$BASEDIR/src/core/models/Models.hpp) \
        $$quote($$BASEDIR/src/ui/ChatController.hpp) \
        $$quote($$BASEDIR/src/ui/DmListController.hpp) \
        $$quote($$BASEDIR/src/ui/MainPageController.hpp) \
        $$quote($$BASEDIR/src/ui/ServerListController.hpp)
}

CONFIG += precompile_header

PRECOMPILED_HEADER = $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES += \
        $$quote($$BASEDIR/../src/*.c) \
        $$quote($$BASEDIR/../src/*.c++) \
        $$quote($$BASEDIR/../src/*.cc) \
        $$quote($$BASEDIR/../src/*.cpp) \
        $$quote($$BASEDIR/../src/*.cxx) \
        $$quote($$BASEDIR/../src/core/*.c) \
        $$quote($$BASEDIR/../src/core/*.c++) \
        $$quote($$BASEDIR/../src/core/*.cc) \
        $$quote($$BASEDIR/../src/core/*.cpp) \
        $$quote($$BASEDIR/../src/core/*.cxx) \
        $$quote($$BASEDIR/../src/core/client/*.c) \
        $$quote($$BASEDIR/../src/core/client/*.c++) \
        $$quote($$BASEDIR/../src/core/client/*.cc) \
        $$quote($$BASEDIR/../src/core/client/*.cpp) \
        $$quote($$BASEDIR/../src/core/client/*.cxx) \
        $$quote($$BASEDIR/../src/core/discord/*.c) \
        $$quote($$BASEDIR/../src/core/discord/*.c++) \
        $$quote($$BASEDIR/../src/core/discord/*.cc) \
        $$quote($$BASEDIR/../src/core/discord/*.cpp) \
        $$quote($$BASEDIR/../src/core/discord/*.cxx) \
        $$quote($$BASEDIR/../src/core/models/*.c) \
        $$quote($$BASEDIR/../src/core/models/*.c++) \
        $$quote($$BASEDIR/../src/core/models/*.cc) \
        $$quote($$BASEDIR/../src/core/models/*.cpp) \
        $$quote($$BASEDIR/../src/core/models/*.cxx) \
        $$quote($$BASEDIR/../src/ui/*.c) \
        $$quote($$BASEDIR/../src/ui/*.c++) \
        $$quote($$BASEDIR/../src/ui/*.cc) \
        $$quote($$BASEDIR/../src/ui/*.cpp) \
        $$quote($$BASEDIR/../src/ui/*.cxx) \
        $$quote($$BASEDIR/../assets/*.qml) \
        $$quote($$BASEDIR/../assets/*.js) \
        $$quote($$BASEDIR/../assets/*.qs) \
        $$quote($$BASEDIR/../assets/images/*.qml) \
        $$quote($$BASEDIR/../assets/images/*.js) \
        $$quote($$BASEDIR/../assets/images/*.qs) \
        $$quote($$BASEDIR/../assets/images/icons/*.qml) \
        $$quote($$BASEDIR/../assets/images/icons/*.js) \
        $$quote($$BASEDIR/../assets/images/icons/*.qs) \
        $$quote($$BASEDIR/../assets/images/icons/accent/*.qml) \
        $$quote($$BASEDIR/../assets/images/icons/accent/*.js) \
        $$quote($$BASEDIR/../assets/images/icons/accent/*.qs)

    HEADERS += \
        $$quote($$BASEDIR/../src/*.h) \
        $$quote($$BASEDIR/../src/*.h++) \
        $$quote($$BASEDIR/../src/*.hh) \
        $$quote($$BASEDIR/../src/*.hpp) \
        $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS = $$quote($${TARGET}.ts)
